# Generated by Django 3.2 on 2021-05-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('team_name', models.TextField()),
                ('teams_blog', models.TextField()),
                ('team_website_url', models.TextField()),
            ],
        ),
    ]
